language: java
jdk:
  - oraclejdk8
notifications:
  email:
    recipients:
      - francois.fouquet@uni.lu
      - gregory.nain@uni.lu
      - thomas.hartmann@uni.lu
      - assaad.moawad@uni.lu
      - ludovic.mouline@uni.lu
      - andrey.boytsov@uni.lu
    on_success: change
    on_failure: change

#Compile only master branch
branches:
  only:
    - master

env:
  - TRAVIS_NODE_VERSION="4"

before_install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - node -v